service: telegram-bot

plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-domain-manager

custom:
  secrets: ${file(./secrets.yml):${self:provider.stage}}
  customDomain:
    domainName: ${self:custom.secrets.DOMAIN}
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'develop'}
  apiGateway:
    shouldStartNameWithService: true
  environment:
    API_KEY_EXAMPLE: ${self:custom.secrets.API_KEY_EXAMPLE}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: any
          path: /{any+}
